version: '3.7'
services:
  dnsmasq:
    image: jpillora/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./efi:/srv/tftpboot/efi
    network_mode: host
    entrypoint: []
    command: |
      sh -c "
        if [ -z '${INTERFACE}' ] ; then
          echo 'Usage: INTERFACE=eth0 SUBNET=192.168.1.0 NETMASK=255.255.255.0 docker compose up'
          exit 1
        fi
        dnsmasq --no-daemon --interface=${INTERFACE} --dhcp-range=${SUBNET:-192.168.1.0},proxy,${NETMASK:-255.255.255.0}
      "
