name: Build

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/checkout@v2

      - name: Install packages
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           gcc-aarch64-linux-gnu iasl mtools subversion \
                           lzma-dev uuid-dev
          sudo ln -sf /bin/bash /bin/sh 

      - name: Build everything
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          make -j8

      - name: Create release
        id: create_release
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload (tftpboot.zip)
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: tftpboot.zip
          asset_path: tftpboot.zip
          asset_content_type: application/zip
